### ISSUE TITLE
running through vpn issue

### ISSUE THREAD

**Issue by soupnatzi** [d3mondev/puredns#15]
when connected to vpn the tool does not work but when ran with out vpn it kills my local internet if the list of domains is big but if small it works.

setup:
root@kali:~# uname -a
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux

is there anyway around this or is the tool intended to be ran in a vps?

**Comment by d3mondev** [comment]
You can try to limit the rate of the queries with the --rate-limit option with values between 100 and 1000 and see if it helps. The default is unlimited and it can easily flood a VPN or residential internet connection.

But it's definitely intended to be run on a VPS.
