### ISSUE TITLE
PureDNS stucks at "Validating domains against trusted resolvers"

### ISSUE THREAD

**Issue by proabiral** [d3mondev/puredns#16]
PureDNS stucks at `Validating domains against trusted resolvers` when all domains from the list are filtered out by wildcard detection or no domain resolves . 

Examples : 

`echo "nxdomain.facebook.com" | puredns resolve`

`echo "wildcard.paypal.com" | puredns resolve`

**Comment by d3mondev** [comment]
I'm unable to reproduce on my side. Do you have any additional information to repro the issue?

```
$ echo "nxdomain.facebook.com" | puredns resolve
                          _
                         | |
 _ __  _   _ _ __ ___  __| |_ __  ___
| '_ \| | | | '__/ _ \/ _` | '_ \/ __|
| |_) | |_| | | |  __/ (_| | | | \__ \
| .__/ \__,_|_|  \___|\__,_|_| |_|___/
| |
|_|                     puredns v2.0.1

Fast and accurate DNS resolving and bruteforcing

Crafted with <3 by @d3mondev
https://github.com/sponsors/d3mondev

------------------------------------------------------------
[+] Mode                 : resolve
[+] File                 : stdin
[+] Resolvers            : resolvers.txt
[+] Rate Limit           : unlimited
[+] Rate Limit (Trusted) : 500 qps
[+] Wildcard Threads     : 100
[+] Wildcard Tests       : 3
------------------------------------------------------------

Resolving domains with public resolvers
Processed: 1 Rate: 1 Elapsed: 00:00:00

Detecting wildcard root subdomains
[ETA 00:00:00] |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0/0 queries: 0 (time: 00:00:00)

Validating domains against trusted resolvers
Processed: 0 Rate: 0 Elapsed: 00:00:00

No valid domains remaining.
```

Same thing with wildcard.paypal.com (and wildcard.paypal.cn).

**Comment by d3mondev** [comment]
Does `dig @8.8.8.8 nxdomain.facebook.com` work for you? puredns uses 8.8.8.8 as a trusted resolver by default. If the IP is banned or blocked from accessing 8.8.8.8, it's possible that the wildcard detection and validation doesn't work as expected.

The solution would be to specify a file containing alternative trusted resolvers with `--resolvers-trusted` and adjust the rate limit with `--rate-limit-trusted`. 9.9.9.10 would be a viable alternative, with a much lower rate limit (I would guess with a maximum of 20-50 queries per second).

**Comment by proabiral** [comment]
@d3mondev ,

Thank you for such a quick and detailed response.

Seems like this was caused by [a bug](https://github.com/blechschmidt/massdns/issues/50) in massdns rather than puredns. Updating the massdns to latest version fixed the issue.

Thank you once again for the help and creating such an awesome tool.

**Comment by d3mondev** [comment]
Good to know! Thanks for linking the original issue!
