### ISSUE TITLE
puredns error: error resolving domains: exit status 1

### ISSUE THREAD

**Issue by atikrahman1** [d3mondev/puredns#17]
Hi ,

Everything seems fine. Massdns installed but puredns throwing error that `puredns error: error resolving domains: exit status 1`

I trace the issue. The problem is actually in massdns. that massdns will not allow you to run massdns without supplying --root argument when you are the root user. Puredns doesn't supply the --root argument while running the massdns. 

![image](https://user-images.githubusercontent.com/25384315/127112475-268f78ce-b878-4af4-a7d4-9eaa9fae8ff8.png)

**Comment by atikrahman1** [comment]
I have solved the issue by editing the 

https://github.com/d3mondev/puredns/blob/dc73bee6d3b580ffc82db7602a9d9708b1659269/pkg/massdns/runner.go#L41
What I did is to solve this problem edit this code and added ```--root``` argument end of the command.

```go
args := []string{"-q", "-r", resolvers, "-o", "Snl", "-t", "A", "--root", "--retry", "REFUSED", "--retry", "SERVFAIL", "-w", output}
```

and rebuild the package.

**step to solve** 

1. Go to ```/root/go/pkg/mod/github.com/d3mondev/puredns/v2@v2.0.1/pkg/massdns/runner.go```

2. Edit and save the file

3. ```cd /root/go/pkg/mod/github.com/d3mondev/puredns/v2@v2.0.1```

4. `go install`

**Comment by gprime31** [comment]
Should PIN this.
Great find!

**Comment by d3mondev** [comment]
Puredns now supports running massdns as root since v2.1.0!

**Comment by b-hermes** [comment]
For some reason I'm using the latest version and I still have this error. 
`puredns error: error resolving domains: exit status 1`

What else can I try?

**Comment by mujtabaa-dev** [comment]
I'm using the latest version and I have the same problem ? is there any update or temporary solution ?
