### ISSUE TITLE
Heavy Load on Wi-Fi Router

### ISSUE THREAD

**Issue by Archurcl4w** [d3mondev/puredns#18]
Hello I am running
puredns bruteforce wordlist.txt domain.com -w brute.txt
where my wordlist is 3 Million . After around 4 to 5 hours it gave a heavy load on my Wi-Fi router and it did not work properly. Disconnected many times and network speed also reducing so unable to open proper web pages. It almost fried the router. I can't finish this test.
To solve it and effectively running should I use -l flag  and set the value between 2000-10000 . If so which will be correct value for 3 Million wordlist ?Further should I also use --wildcard-batch 1000000 ? I am running on home system without VPS.  Kindly enlighten me as well as to further improvement of puredns in such similar cases .Is require any other --wildcard  flags ?

**Comment by d3mondev** [comment]
puredns can easily overload Wifi, residential connections and even some VPS providers network.

Controlling the rate of queries per second with the --rate-limit and --rate-limit-trusted flags is the correct way to try to limit the bandwidth. As to what exact value to use, it depends on each connection and should be figured out with trial and error.
