### ISSUE TITLE
Go get issue in 1.17

### ISSUE THREAD

**Issue by d1pakda5** [d3mondev/puredns#25]
Since go get is  deprecated    using go install throwing this error how to resolve this

go install github.com/d3mondev/puredns@latest

go install: github.com/d3mondev/puredns@latest: module github.com/d3mondev/puredns@latest found (v1.0.3), but does not contain package github.com/d3mondev/puredns

**Comment by d3mondev** [comment]
The correct command to install puredns with go 1.18 is:

`go install github.com/d3mondev/puredns/v2@latest`

Thanks for bringing it to my attention, I'll update the docs :)
