### ISSUE TITLE
Not quite sure how to add the path to massdns in the PATH environment variable

### ISSUE THREAD

**Issue by apskis** [d3mondev/puredns#26]
I know this may be obvious for a lot of people but it wasn't for me. I am working on ubuntu 20 and I am not quite sure how to add the path to massdns in the PATH environment variable. Can someone assist? 

Do I simply add the following to my ./profile or to ./bashrc?
PATH=/usr/local/bin/massdns

**Comment by d3mondev** [comment]
If you compile and install massdns according to the instructions, make sure to run the last step as root with sudo.

```
sudo make install
```

This will copy massdns into /usr/local/bin, which should already be in the PATH environment variable.
