### ISSUE TITLE
ADD https://github.com/d3mondev/puredns/issues/17 to next update please.

### ISSUE THREAD

**Issue by gprime31** [d3mondev/puredns#27]
add https://github.com/d3mondev/puredns/issues/17
so massdns can run as root on VPS
Thanks.

**Comment by sn00pyd0g3** [comment]
+1

**Comment by sn00pyd0g3** [comment]
Temporary solution for people who do not want to compile the project:
wrap the massdns with the bash script
```
#!/bin/bash

/usr/local/bin/massdns_exe --root $*
```

**Comment by d3mondev** [comment]
Puredns now supports running massdns as root since v2.1.0!
