### ISSUE TITLE
add analysis of the discovered subdomain names to find naming patterns

### ISSUE THREAD

**Issue by nycalex** [d3mondev/puredns#31]
subdomain names frequently have patterns of various kinds.  Doing initial pass at the name discovery would produce an initial subdomain list. Searching thought that list and recognizing those patterns would enable you to use these patterns as an anchor for second brut-forcing round.

**Comment by d3mondev** [comment]
Interesting idea, but I think it's better to leave this to other tools. Domain permutators like ripgen and gotator work well for this.
