### ISSUE TITLE
Any way to speed up wildcard filtering?

### ISSUE THREAD

**Issue by marcelo321** [d3mondev/puredns#33]
I am resolving a lot of subdomains pretty fast, but when it comes to wildcard filtering it just takes forever and I don't know if it would be possible to speed it up, it takes an absurd amount of time:

```
Resolving domains with public resolvers
Processed: 2253265 Rate: 7514 Elapsed: 00:05:16

Detecting wildcard root subdomains
[ETA 52:12:09] |█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 5616/1553671 queries: 5718 (time: 00:10:55))
```

5 minutes to resolve, ~52 hours to wildcard filtering (it is updated all the time), the queries go so slow even thought I didn't provide any `--wildcard-batch` value

Does the `--rate-limit-trusted` flag affect the wildcard filtering (does it use the trusted resolvers)? or just `-t` for threads and `--wildcard-batch` affect it? because I don't see much changes from the last 2 flags, but I notice some different when changing the limit of trusted resolvers

**Comment by d3mondev** [comment]
I've seen this happen on some targets that drop the traffic from resolvers producing too many queries. Unfortunately not much to do in this case, besides trying to add more trusted resolvers and rate limiting. But even then, some target are pretty resistant to bruteforcing.
