### ISSUE TITLE
binary release 

### ISSUE THREAD

**Issue by SkyperTHC** [d3mondev/puredns#36]
Please make a pre compiled binary for x86/arm available.

**Comment by d3mondev** [comment]
Thanks for the suggestion. I don't plan to make binary releases for now, but I'll keep this in mind if I do!

**Comment by d3mondev** [comment]
Reopening. Will probably support binary releases!

**Comment by d3mondev** [comment]
Puredns now has binary releases since v2.1.0! I could use some help testing them though. Please open a new issue if they don't work on your system.

Thank you!
