### ISSUE TITLE
Wildcard root question

### ISSUE THREAD

**Issue by riramar** [d3mondev/puredns#38]
Thanks for the amazing tool!
When you have multiple subdomains under the same wildcard root, puredns won't return any subdomain.
For example:

au.site.yahoo.com
matrixcollectibles.site.yahoo.com

Wouldn't be interesting to return at least one subdomain from the list above?
If an user is filtering valid domains for security testing, he/she could miss valid subdomains from wildcard roots domains.

**Comment by d3mondev** [comment]
Hi,

Unfortunately this is not something that puredns can detect by looking at the DNS entries. It would require a tool that fetches the web page and compares the results, which it is not suited for. I would probably use ffuf or something similar instead?
