### ISSUE TITLE
[Feature request] Quiet mode

### ISSUE THREAD

**Issue by shelld3v** [d3mondev/puredns#4]
**puredns** allows writing results into a file, so the CLI output should be optional

**Comment by d3mondev** [comment]
In the current version, all the informative output is sent to stderr. You can quiet the output by running it like so:

`puredns resolve domains.txt 2>/dev/null`

and only the domains found will be shown.

In puredns v2, there will be a -q flag to explicitly quiet the output to make this easier.

**Comment by shelld3v** [comment]
Cool
