### ISSUE TITLE
[Feature request] Validate DNS resolvers

### ISSUE THREAD

**Issue by shelld3v** [d3mondev/puredns#5]
Like Amass, puredns should perform an initial scan against DNS resolvers when starting, in order to see if any resolver has died (some resolvers on public-dns.info are taken down usually)

**Comment by d3mondev** [comment]
In this specific use case, this is typically not an issue - massdns will retry up to 50 times with different resolvers if it fails to get a response. Testing the resolvers on each launch would slow down the process too much - instead, it would be more efficient to have a recurring cron task that obtains fresh resolvers and tests them with dnsvalidator.

That said, it's possible that I add a feature to download and test resolvers in puredns in the future.

**Comment by d3mondev** [comment]
I've decided not to go forward with adding more features like this to puredns. I think it would be better suited for a standalone tool.
