### ISSUE TITLE
add another wildcard (or 2 ) to the bruteforce.

### ISSUE THREAD

**Issue by gprime31** [d3mondev/puredns#54]
Hi,
Love this tool.
so now the bruteforce is like: puredns bruteforce wordlist.txt "www.*.example.com" with a single wordlist.

can you make it like puredns bruteforce wordlist.txt "*.www.*.example.com"  using 2 wordlists?

or  three or more?

example:  puredns bruteforce wordlist.txt "site*.www.*.example*.site.com"

**Comment by d3mondev** [comment]
Hi, thanks for your suggestion. This is not something I would consider implementing directly in puredns. Instead, I would probably generate the list of domains to resolve externally and pipe it to puredns.

A small utility like https://github.com/d3mondev/crossjoin can help to generate those lists.

Closing for now, but let me know if you have any other ideas.
