### ISSUE TITLE
[Feature request] Alterations

### ISSUE THREAD

**Issue by shelld3v** [d3mondev/puredns#6]
Something like [altdns](https://github.com/infosec-au/altdns), as an optional flag of `resolve`

**Comment by d3mondev** [comment]
There are so many different ways to generate permutations and alterations that I think this is better handled by external tools. There are already many that do this in different ways and their output can be piped to puredns. After consideration I will continue to focus puredns on resolving and detecting wildcards. Thanks for your suggestion!
